### ISSUE TITLE
feat(populate): populate ordered data

### ISSUE THREAD

**Issue by benoj** [prescottprue/react-redux-firebase#239]
Is it possible to have ordered data that has been populated?

**Comment by prescottprue** [comment]
@benoj No, `populatedDataToJS` does not currently handle ordered data in `v1` (but is a planned feature of `populate` in `v2`). You can however do the population from redux by hand since the data is available.

That means that data needed for populating can be gathered with `populates` in your query config, but you will need to do the mapping yourself.

Something like this (if using v1):

```jsx
const populates = [{ child: 'owner', root: 'users' }]

@firebaseConnect([
  { path: 'todos', populates}
])
@connect(
  (state => ({
    todos: dataToJS(state.firebase, 'todos'),
    populatedTodos: firebase.getIn(['data', 'todos'])
      ? firebase
          .getIn(['data', 'todos'])
          .map(todo => ({
            ...todo.toJS(),
            // get owner from users in redux defaulting to id if user not found
            owner: dataToJS(firebase, `users/${todo.get('owner')}`, todo.owner) 
          }))
          .toJS()
      : [],
  })
)
```

Obvisouly this is not as clean as directly using `populatedDataToJS` in `v1.*.*` or `populate` in `v2.*.*`

**Comment by benoj** [comment]
Thanks, will look to migrate to v 2.0.0 

Just a further general question w.r.t ordered data. My data looks as below

```
comments:
 -KrcAcNlMnoEIGK7vYy5
     author: "30bp2ABAAwXtXR9zovUNTnz3uS62"
     text: "bing"
     timestamp: 1502842062097
 -KreuqJMGaXxIKZiwJUz
     author: "30bp2ABAAwXtXR9zovUNTnz3uS62"
     text: "bong"
     timestamp: 1502884879319

```
And my query looks like
```

const populates = [
{ child: 'author', root: `users` }
]

@firebaseConnect((props) => {
  const {currentOrg, candidateId} = props
  return [
    { path: `/comments`, populates, queryParams: ['orderByChild=timestamp']}
  ]
})
```

The comments are coming back as an object, is there a better way to query this so that they are coming back as an ordered list?
